### ISSUE TITLE
ps1 can working but ps2 mode can't working 

### ISSUE THREAD

**Issue by hpx1984** [sd2psx/pcb#2]
Dear Sir

this really a great project for PSx
i very like it 

i build 2sets and can working on PS1
i also saw there has PS2 mode and then it change it to ps2 mode and plug it to PS2 , OLED no display and no working 
and then i plug it to PS1 still no display and no working 

any possible for fix it ？or it is damage 
please help ,many thanks sir

**Comment by xyzz** [comment]
First update to the latest firmware from https://github.com/sd2psx/firmware/releases/tag/latest
After that, it should show a fatal error message on the OLED screen if there's any error. If PS1 mode works but PS2 mode doesn't it may be an error with the PSRAM chip:
![image](https://user-images.githubusercontent.com/1065521/212622713-837c9384-3fbd-42ab-982a-38084da2bd3f.png)
If it's still not showing anything on the screen after firmware update, to get debug output you can:
1) solder to UART (TX/RX/G pins) on the back, then check output with 3000000 baud mode
2) after this line <https://github.com/sd2psx/firmware/blob/076baf6d56afa501adc0e12e0e616a930d5d69dd/src/main.c#L64> add:
```
    stdio_usb_init();
    sleep_ms(5000);
```
then it will provide a USB COM port for debugging messages, you can plug it into a PC and look for any error messages.

**Comment by xyzz** [comment]
Also after you change to PS2 mode, don't plug it into PS1 because it may damage the chip or the console.

**Comment by hpx1984** [comment]
Dear Sir xyzz

many thanks your quickly replied 
yes , i saw the information you remind the user after confirmed change to PS2 mode

actually i had not mount the U4 on board so that is the problem way could not working after change to PS2  on my side，right？
i will try to buy some U4 for complete the build , now just used it on PS1

**Comment by hpx1984** [comment]
Dear Sir xyzz

many thanks your quickly replied 
yes , i saw the information you remind the user after confirmed change to PS2 mode

actually i had not mount the U4 on board so that is the problem way could not working after change to PS2  on my side，right？
i will try to buy some U4 for complete the build , now just used it on PS1

**Comment by xyzz** [comment]
yes, it is required for PS2 mode to work
