### ISSUE TITLE
Black screen on PS1 and Ps2 mode

### ISSUE THREAD

**Issue by Tungraider** [sd2psx/pcb#3]
Dear Sir

I really liked the project but I'm not having any luck

the card works connected to the usb but on the consoles it does not show a sign of life, it always appears a black screen on the oled and the console does not recognize it either

Thanks

**Comment by xyzz** [comment]
Please install the usb debug firmware from https://github.com/sd2psx/firmware/releases/download/latest/sd2psx_usb_debug.uf2 and then provide a log from tera term - https://ttssh2.osdn.jp/index.html.en

![](https://cdn.discordapp.com/attachments/1027294049624920194/1066572204923429005/tera1.png)
![](https://cdn.discordapp.com/attachments/1027294049624920194/1066572205221216306/tera2.png)

**Comment by Tungraider** [comment]
ok, i got this log
![log](https://user-images.githubusercontent.com/107059804/223011594-59427ca4-ed27-4362-9dc7-94369d43a381.jpg)

**Comment by xyzz** [comment]
There is no error here, if it's still not working maybe it has bad contact with the memory card slot? Check all of the termination resistors on the pcb look good, also check if there are any shorts on the pcb. Did you order this from a store or make one yourself?

**Comment by Tungraider** [comment]
Hi sir
Again I apologize, after checking all the components I discovered a poorly soldered diode by the company that I ordered the assembled pcb and after soldering the same the sd2psx worked perfectly, thanks for the feeback and congratulations for the project
