### ISSUE TITLE
SW1 and Sw2 are on the wrong side of the board

### ISSUE THREAD

**Issue by Gardosen** [sd2psx/pcb#4]
Hello,

to redesign a case from someone for the rev4 boards, i tried to export your kicad project to blender and over to fusion.
while doing this i noticed this.

![image](https://github.com/sd2psx/pcb/assets/415867/c2342cea-d9a7-4fca-b24e-61df340b218b)

i could be mistaken, but it should look like this, should it?
![image](https://github.com/sd2psx/pcb/assets/415867/7fcec397-b741-4b71-851e-83ed21056f25)

Kind regards
Gardosen

**Comment by xyzz** [comment]
The first image is the correct position; it requires to cut the OLED display module a little:

![PXL_20230511_0150532732](https://github.com/sd2psx/pcb/assets/1065521/9a9f9aaf-3a87-4699-927a-2f6527ade762)

If put on the other side, the buttons clip through the case like so

![tall](https://github.com/sd2psx/pcb/assets/1065521/b0108429-36f3-44dd-b914-adae93f41b97)

It's not bad enough to cause compatibility issues with other hardware plugged in, like a bluetooth controller adapter, but you'd either have to add a bump or a hole at the bottom and I figured cutting a bit of oled pcb is a better compromise.

**Comment by xyzz** [comment]
Also check out the existing rev4 case design in https://github.com/sd2psx/case/tree/main/rev4

**Comment by Gardosen** [comment]
Hey, 

thanks for letting me know, i'm sorry for the disturbance, thanks for the detailed explenation where my mistake is, i indeed forgot to put the bottom plate on the design to check the conflict with the buttons.

kind regards
Marco
